USE EduPro
GO

--CREAR UN SP PARA LISTAR LOS MEDICOS DE UN DETERMINADO NOMBRE DE DISTRITO
CREATE PROCEDURE SP_LIST_MED_DIST
@distrito TEXT
AS

SELECT.direccion ,'NombreyApellidos' = CONCAT(nombres,' ',apellidos) FROM medico m
INNER JOIN direccion d on m.id_direccion = d_id_direccion
INNER JOIN ubigeo u on d.id_ubigeo = u_id_ubigeo

WHERE DISTRITO = @distrito

--FUNCIONES ESCALARAS
--CREAR UNA FUNCION QUE DEVUELVA LA CANTIDAD DE UBIGEOS

CREATE FUNCTION FN_CANT_UBI() RETURN INT
AS
  BEGIN
       DECLARE @CANT_UBI INT
       SELECT @CANT_UBI = COUNT(*) FROM UBIGEO
       RETURN @CANT_UBI
  END

--LLAMAR A UNA FN
SELECT DBO.FN_CANT_UBI()

/*Ejercicio 1
Crear una funcion que devuelva la cantidad 
de ubigeos de un determinado dpto. */

CREATE FUNCTION FN_CANT_UBI_DPTO(@DPTO NVARCHAR(50)) RETURNS NVARCHAR(50)
AS
  BEGIN
        DECLARE @CANT_UBI_DPTO NVARCHAR(50)
		SELECT @CANT_UBI_DPTO - COUNT(*) FROM UBIGEO
		WHERE CAST(DEPARTAMENTO AS NVARCHAR(50)) - @DPTO
		RETURN @CANT_UBI_DPTO
  END

---LLAMAR A UNAFN
SELECT DBO.FN_CANT_UBI_DPTO('APURIMAC')


---FUNCIONES DE TABLA EN LINEA
--CREAR UNA FUNCION QUE LISTE TODOS DPTO CON SUS PROVINCIAS
--LOS UBIGEOS
CREATE FUNCTION FN_LIS_UBI() RETURNS TABLE
AS
  RETURN(SELECT CAST (departamento AS nvarchar(50)) as'Dpto',
         CAST(PROVINCIA AS nvarchar(50)) as'Prov'
  FROM UBIGEO)


--LLAMAR A UNA FUN
SELECT distinct dpto, prov from dbo.FN_LIS_UBI
SELECT * FROM DBO.FN_LIS_UBI

-----
--CREAR UN FN QUE DEVUELVA LAS PROVINCIAS
--DE UN DETERMINADO DPTO
CREATE FUNCTION FN_LIS_UBI_DPTO(@DPTO nvarchar(50)) RETURNS TABLE
AS
  RETURN(SELECT CAST(departamento AS nvarchar(50)) as 'Dpto',
         CAST(PROVINCIA AS nvarchar(50))as 'Prov'
		 FROM Ubigeo
		 WHERE CAST(departamento AS nvarchar(50)) = @DPTO)

--LLAMAR A UNA FN
SELECT DISTINCT DPTO, PROV FROM DBO.FNLIS_UBI_DPTO('AMAZONAS')

/*TAREA*/

-----1.- CREAR UNA FUNCION QUE INDIQUE LA CANTIDAD DE MEDICOS POR ESPECIALIDAD

-----2.- CREAR UNAFUNCION QUE LISTE LOS MEDICOS POR UNA DETERMINADA ESPECIALIDAD
------- Y QUE ATENDIERON UNA CONSULTA EN UNA FECHA DETERMINADA