--LISTAR CLIENTES
SELECT *FROM CUSTOMERS

--LISTAR SOLO NOMBRES DE COMPAÑIA, DIRECCION, CIUDAD Y PAIS DE ORIGEN
SELECT COMPANYNAME, [ADDRESS], CITY, COUNTRY FROM CUSTOMERS

--LISTAR LOS DETALLES DE PEDIDO
SELECT *FROM [Order Details]

--LISTAR TODOS LOS CLIENTES DONDE SU PAIS DE ORIGEN SEA 
-- IGUAL A ALEMANIA
SELECT *FROM CUSTOMERS
WHERE COUNTRY = 'GERMANY'

--LISTAR TODOS LOS PEDIDOS
SELECT*FROM ORDERS

--LISTAR TODOS LOS PEDIDOS DONDE SU FECHA DE PEDIDO(ORDERDATE)
--SEA DEL AÑO 2016
SELECT *FROM ORDERS
WHERE YEAR(ORDERDATE) = '2016'

--LISTAR TODOS LOS PRODUCTOS
SELECT *FROM PRODUCTS

--LISTAR EL PRODUCTO QUE TENGAN EL MINIMO PRECIO
SELECT PRODUCTNAME, MIN(UNITPRICE) FROM PRODUCTS

--LISTAR LA CANTIDAD DE PEDIDOS(ORDERID)
--POR CADA PAIS DESTINO (SHIPCOUNTRY)
SELECT SHIPCOUNTRY, COUNT(ORDERID) AS 'Cantidad de Pedidos'
FROM ORDERS GROUP BY SHIPCOUNTRY

SELECT *FROM EMPLOYEES
--LISTAR LOS NOMBRES DE LOS EMPLEADOS
--SU CARGO (TITLE) Y SU FECHA DE NACIMIENTO
--SUS NOMBRES Y APELLIDOS DEBEN ESTAR EN UNA SOLA COLUM
SELECT CONCAT(lastname, ' ',firstname) as 'Empleado',
title as 'Cargo', birthdate as 'Fec_nac'
FROM EMPLOYEES
WHERE MONTH(BIRTHDATE) = '01'

--CREAR UNA LISTA DE TODAS LAS TABLAS QUE SEAN DE ORIGEN PERSONA
--SOLOS SUS NOMBRES PRINCIPALES E IDENTIFICARLOS CON UNA COLUMNA QUE
--DIFERENCIE A CADA UNO DE ELLOS
SELECT COMPANYNAME, 'TIPO_PERSONA' = 'PROVEEDOR'
FROM SUPPLIERS

UNION

SELECT COMPANYNAME, TIPO_PERSONA = 'CLIENTE'
FROM CUSTOMERS

UNION

SELECT CONCAT(LASTNAME, ' ', FIRSTNAME) AS 'EMPLEADO', TIPO_PERSONA = 'TRABAJADOR'
FROM EMPLOYEES

--CONTAR LA CANTIDAD DE PEDIDOS (ORDERID) POR CADA CLIENTE DE
--LA TABLA ORDERS
--SOLO LISTA A LAS MAYORES DE 20

SELECT CUSTOMERID, COUNT(ORDERID) AS 'Cantidad de Pedidos'
FROM ORDERS
GROUP BY CUSTOMERID
HAVING COUNT(ORDERID) > 20
ORDER BY [Cantidad de Pedidos] DESC;